### ISSUE TITLE
Testing on environments with no postgres root password set is currently not possible

### ISSUE THREAD

**Issue by rbclark** [CrunchyData/pgstigcheck-inspec#11]
I have a configuration that I am wondering if it is possible/wise to support for with profile. I am currently setting up postgres with no postgres password, and I have noticed that this makes it impossible to run this STIG check. Is this on purpose, since it is considered insecure to run in this configuration, or for a different reason?

**Comment by sharmay** [comment]
It is required to have password for OS user as well DB superuser for security.
