### ISSUE TITLE
This profile is written for the PostgreSQL 9.x STIGv1, the current version 4 has many new controls

### ISSUE THREAD

**Issue by asturtevant** [CrunchyData/pgstigcheck-inspec#19]
This profile is written for the PostgreSQL 9.x STIGv1, the current version 4 has many new controls.

Could this profile be updated to reflect the new changes in the PostgreSQL 9.x STIGv4.

The following new controls would need to be added:

- V-72843 
- V-72847
- V-72853 
- V-72855 
- V-72885
- V-72889
- V-72907
- V-72913
- V-72915 
- V-72921 
- V-72923
- V-72925 
- V-72927
- V-72929
- V-72933
- V-72939 
- V-72941
- V-72945
- V-72951 
- V-72969
- V-72975 
- V-72977 
- V-72985
- V-72997 
- V-73007 
- V-73009 
- V-73039
- V-73043 
- V-73053
- V-73059

**Comment by hunleyd** [comment]
from https://www.stigviewer.com/stigs, I see https://www.stigviewer.com/stig/postgresql_9.x/ which only shows v1. Where are you seeing a v4?

**Comment by asturtevant** [comment]
Sorry, that should ready version 1, revision 4, from https://iase.disa.mil/stigs/Pages/a-z.aspx

**Comment by aaronlippold** [comment]
Just a note stigviewer.com is not an official resource. The only official resources on the IASE.disa.Mil site.

**Comment by hunleyd** [comment]
Good to know @aaronlippold ! Thanks for that. I'll look into these controls and see what is needed.

**Comment by aaronlippold** [comment]
Please ignore this stupid voice translation issues in my last comment :-)
great glad to hear it. I'm actually going to spend a little time this
weekend to see if I can build a better web-based Sting viewer that uses
IADE as it's so source to help the community out a bit.

That said I think I will also push up a PR to the repo to adjust the readme
to point to the correct reference of the stig document on the IASE website.

Please feel to reach out to Alicia as you're working through the controls
given that she is on the hook to update the profiles for both the system
implementation and the RDS overlay.

**Comment by aaronlippold** [comment]
With the update to v1.6 these issues should be resolved
