### ISSUE TITLE
Issue with use of tags - tags overwrite key value pairs

### ISSUE THREAD

**Issue by aaronlippold** [CrunchyData/pgstigcheck-inspec#3]
In the controls, when we tag the controls with multiple cci's or nist 800-53 tags you must tag them in an array rather than individual controls. 

The key/value pair will take the last value set. 
```
  tag "cci": ["CCI-000382","CCI-001762"]
  tag "nist": ["CM-7 b", "CM-7 (1) (b)", "Rev_4"]
```
To ensure you are getting the right data.

**Comment by steve-hetzel** [comment]
PR submitted to reflect this change for control V-72841.rb.  Grep of the other controls looking for this pattern came back negative.

**Comment by steve-hetzel** [comment]
As a follow-up, I have scripted a count of tags in each control and have not yet found any other duplicates.  I did find however that V-72987.rb is missing all of the tags (e.g. severity, gtitle, gid, rid, stig_id, etc.) as well as the impact weighting.  We will want need to determine appropriate values and populate accordingly.
